// Always shows real, non-AI-generated crisis resources. This component is
// intentionally static — nothing here is generated by the analysis model.
export default function CrisisResourcesCard() {
  return (
    <div className="card p-5 border-2 border-red-200 bg-red-50/60">
      <h3 className="font-semibold text-red-700 mb-2">If you're in crisis right now</h3>
      <ul className="text-sm text-red-800 space-y-1">
        <li>United States: call or text <strong>988</strong> (Suicide & Crisis Lifeline)</li>
        <li>UK & ROI: <strong>Samaritans</strong> — 116 123</li>
        <li>India: <strong>iCall</strong> — 9152987821, or <strong>Tele-MANAS</strong> — 14416</li>
        <li>Elsewhere: search "[your country] crisis helpline" or contact local emergency services</li>
      </ul>
      <p className="text-xs text-red-600 mt-2">
        This app is peer support, not emergency care. If you or someone else is in immediate danger, please
        contact local emergency services right away.
      </p>
    </div>
  );
}
